### ISSUE TITLE
Use dependency injection in the filter class

### ISSUE THREAD

**Issue by deviantintegral** [juanolalla/htmlpurifier#10]
Let's not use `\Drupal` unless we have to.

**Comment by juanolalla** [comment]
Can you show me an example of what do you want me to do?

**Comment by deviantintegral** [comment]
In this case, filters are plugins, which means there is a specific interface to implement: `\Drupal\Core\Plugin\ContainerFactoryPluginInterface`. Most of the time, you can implement `\Drupal\Core\DependencyInjection\ContainerInjectionInterface` instead.

Here is [an example from a Queue Worker plugin](https://github.com/Lullabot/media_mpx/blob/aa7ec00fe4a6f727a4cd560a6e37653dce1f91d3/src/Plugin/QueueWorker/NotificationQueueWorker.php). The steps are:

1. Implement the interface and create()
2. Override the constructor, adding additional arguments with your new services.
3. Replace `\Drupal` with `$this->serviceName->(...)` in the code.

https://github.com/Lullabot/media_mpx/blob/8.x-1.x/src/Plugin/QueueWorker/NotificationQueueWorker.php

There's two advantages with this. First, it makes it _possible_ to unit test the code. But to me, even more useful is that the constructor makes it obvious what dependencies your plugin has. Otherwise, you have to read through the whole class to find calls out to `\Drupal`. Sound good?

**Comment by juanolalla** [comment]
Thanks @deviantintegral! Can you review this commit: https://github.com/juanolalla/htmlpurifier/commit/61b4ddee3b9fff5be447b02e0f6356491da121b6 ?

I've needed to create a public setter for the drupalConfig property dependency, otherwise the tests were failing, because of the way the filter is instantiated in setUp().

**Comment by deviantintegral** [comment]
Good stuff! Do you expect this github repository to be active for a while, or are you expecting to push a patch to the d.o module? If the former, we should set up CI on this repository.

I left notes at https://github.com/juanolalla/htmlpurifier/commit/61b4ddee3b9fff5be447b02e0f6356491da121b6 with some suggestions on how you could remove the `setDrupalConfig()` method.

**Comment by juanolalla** [comment]
We no longer need to inject that dependency after the new approach in #11
