### ISSUE TITLE
Default install config file is empty

### ISSUE THREAD

**Issue by deviantintegral** [juanolalla/htmlpurifier#9]
https://github.com/juanolalla/htmlpurifier/blob/dev/config/install/htmlpurifier.config_directives.yml

Should it be deleted or filled with the default config?

Also, do we need a config schema?

**Comment by juanolalla** [comment]
After discussing all these pros and cons, I've implemented a settings form with a text area for configuration, instead of files and a config schema.

**Comment by juanolalla** [comment]
Here is the pull request: https://github.com/juanolalla/htmlpurifier/pull/11
